#
# Settings for VDMJ. These override defaults in the code. 
#

# Enable merging of adjacent line comments into a single block comment.
vdmj.parser.merge_comments = true
	
# Enable annotation debugging (default false)
vdmj.annotations.debug = true
